insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (1, 'Rosa nitida Willd.', 95.21, 6, 5385.75, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (2, 'Bauhinia multinervia (Kunth) DC.', 12.29, 8, 1537.6, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (3, 'Iris spuria L. ssp. ochroleuca (L.) Dykes', 119.01, 9, 3880.65, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (4, 'Triumfetta semitriloba Jacq.', 11.37, 7, 5752.88, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (5, 'Pyrola asarifolia Michx. ssp. bracteata (Hook.) Haber', 113.59, 4, 2468.12, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (6, 'Echinomastus gautii (L.D. Benson) Mosco & Zanovello', 15.67, 8, 4631.36, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (7, 'Juncus L.', 105.58, 4, 314.53, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (8, 'Malus ioensis (Alph. Wood) Britton var. texana Rehder', 33.37, 2, 9155.57, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (9, 'Lecanora fuscescens (Sommerf.) Nyl.', 25.25, 5, 3481.59, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (10, 'Pycnanthemum verticillatum (Michx.) Pers. var. pilosum (Nutt.) Cooperr.', 53.69, 6, 3410.1, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (11, 'Hydrocotyle verticillata Thunb. var. fetherstoniana (Jennings) Mathias', 23.84, 6, 7781.19, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (12, 'Madia madioides (Nutt.) Greene', 82.03, 3, 2870.34, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (13, 'Cylindropuntia ×vivipara (Rose) F.M. Knuth (pro sp.)', 135.32, 1, 6949.04, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (14, 'Triglochin palustris L.', 125.37, 9, 9357.25, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (15, 'Ranunculus lappaceus Sm.', 103.28, 7, 6969.54, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (16, 'Penstemon crandallii A. Nelson ssp. atratus D.D. Keck', 74.38, 3, 7722.67, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (17, 'Howeia Becc.', 120.28, 3, 8352.3, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (18, 'Vernicia Lour.', 98.88, 9, 52.82, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (19, 'Yeatesia viridiflora (Nees) Small', 138.69, 2, 3522.24, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (20, 'Aeluropus Trin.', 102.64, 4, 7649.68, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (21, 'Psilolechia clavulifera (Nyl.) Coppins', 22.39, 6, 4269.23, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (22, 'Madia radiata Kellogg', 51.14, 9, 6512.07, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (23, 'Aletris aurea Walter', 148.04, 1, 7559.69, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (24, 'Websteria confervoides (Poir.) S. Hooper', 147.18, 8, 2601.13, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (25, 'Senecio pseudoarnica Less.', 48.92, 1, 3625.78, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (26, 'Lepidium integrifolium Nutt. var. heterophyllum S. Watson', 83.33, 1, 1311.48, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (27, 'Legousia Durand', 87.12, 1, 3443.28, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (28, 'Carex communis L.H. Bailey var. communis', 138.41, 5, 9457.82, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (29, 'Fleischmannia pycnocephala (Less.) R.M. King & H. Rob.', 104.02, 3, 3946.6, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (30, 'Collema pulchellum Ach.', 32.87, 5, 7446.55, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (31, 'Brachiaria (Trin.) Griseb.', 49.59, 6, 9061.24, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (32, 'Silene invisa C.L. Hitchc. & Maguire', 28.94, 3, 4103.92, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (33, 'Aulacomnium heterostichum (Hedw.) Bruch & Schimp.', 57.83, 6, 6077.69, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (34, 'Solanum parishii A. Heller', 135.73, 4, 6542.38, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (35, 'Carex reznicekii Werier', 122.87, 3, 4439.8, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (36, 'Galium hispidulum Michx.', 123.88, 2, 4161.91, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (37, 'Ceanothus ×rugosus Greene (pro sp.)', 108.83, 9, 8149.47, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (38, 'Philadelphus pumilus Rydb. var. ovatus Hu', 8.13, 8, 4475.38, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (39, 'Houstonia acerosa (A. Gray) A. Gray ex Benth. & Hook. f. var. acerosa', 60.99, 3, 9523.21, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (40, 'Hordeum brachyantherum Nevski', 112.71, 7, 4171.8, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (41, 'Apium L.', 101.62, 7, 6220.62, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (42, 'Androsace chamaejasme Wulfen ssp. lehmanniana (Spreng.) Hultén', 54.41, 9, 5543.33, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (43, 'Astragalus leibergii M.E. Jones', 112.29, 2, 7864.5, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (44, 'Draba asterophora Payson var. macrocarpa C.L. Hitchc.', 33.2, 1, 1643.86, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (45, 'Cladonia caespiticia (Pers.) Flörke', 74.11, 8, 5764.01, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (46, 'Flacourtia rukam Zoll. & Moritzi', 144.96, 7, 7228.35, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (47, 'Cladonia chlorophaea (Flörke ex Sommerf.) Spreng.', 92.76, 8, 1423.49, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (48, 'Sesbania tomentosa Hook. & Arn.', 103.31, 5, 4175.68, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (49, 'Dicerandra linearifolia (Elliott) Benth.', 102.23, 8, 9183.4, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (50, 'Bruguiera parviflora (Roxb.) Wight & Arn. ex Griffith', 101.8, 8, 2725.6, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (51, 'Gaillardia pulchella Foug. var. picta (D. Don) A. Gray', 135.96, 2, 9553.79, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (52, 'Hymenopappus artemisiifolius DC.', 103.24, 6, 2250.01, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (53, 'Sibbaldia procumbens L.', 142.17, 3, 5582.34, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (54, 'Ariocarpus fissuratus (Engelm.) K. Schum.', 147.37, 8, 3852.76, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (55, 'Potamogeton diversifolius Raf.', 32.55, 9, 8253.71, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (56, 'Pectis papposa Harv. & A. Gray var. grandis Keil', 8.63, 9, 5521.14, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (57, 'Aeschynomene pratensis Small', 16.14, 6, 4392.85, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (58, 'Larix gmelinii (Rupr.) Rupr. var. japonica (Maxim. ex Regel) Pilg.', 48.86, 2, 7632.64, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (59, 'Phlox gladiformis (M.E. Jones) E.E. Nelson', 146.28, 2, 5555.07, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (60, 'Miconia racemosa (Aubl.) DC.', 87.87, 3, 339.1, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (61, 'Oxytropis huddelsonii A.E. Porsild', 133.86, 5, 9522.86, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (62, 'Campylium polygamum (Schimp.) C.E.O. Jensen', 139.21, 3, 1204.84, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (63, 'Pluchea Cass.', 104.88, 8, 8810.84, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (64, 'Polygala cowellii (Britton) S.F. Blake', 132.09, 5, 4071.4, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (65, 'Iris sanguinea Hornem.', 10.21, 4, 9419.74, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (66, 'Calyptranthes estremenae Alain', 114.26, 4, 8615.38, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (67, 'Tragia ramosa Torr.', 43.08, 2, 273.24, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (68, 'Savia Willd.', 52.67, 6, 7724.79, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (69, 'Lomatium canbyi (J.M. Coult. & Rose) J.M. Coult. & Rose', 116.26, 6, 5502.34, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (70, 'Alnus japonica (Thunb.) Steud.', 98.95, 3, 3716.14, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (71, 'Eragrostis frankii C.A. Mey. ex Steud.', 56.46, 2, 7774.65, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (72, 'Malus spectabilis (Aiton) Borkh.', 7.25, 3, 5774.14, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (73, 'Echinocereus viridiflorus Engelm. var. correllii L.D. Benson', 131.17, 6, 8102.25, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (74, 'Coffea canephora Pierre ex Froehner', 70.25, 9, 6472.33, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (75, 'Cynara scolymus L.', 87.7, 3, 7513.99, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (76, 'Poa pseudoabbreviata Rosh.', 92.84, 2, 1665.44, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (77, 'Saxifraga serpyllifolia Pursh', 46.81, 7, 3677.68, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (78, 'Hymenopappus filifolius Hook. var. cinereus (Rydb.) I.M. Johnst.', 99.16, 7, 6744.42, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (79, 'Dudleya blochmaniae (Eastw.) Moran ssp. insularis (Moran) Moran', 48.34, 9, 4666.69, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (80, 'Pseudocryphaea E. Britton ex Broth.', 15.77, 5, 7168.52, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (81, 'Platanthera integrilabia (Correll) Luer', 77.44, 4, 6327.05, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (82, 'Khaya A. Juss.', 4.92, 4, 5988.26, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (83, 'Byrsonima crassifolia (L.) Kunth', 132.15, 8, 1970.39, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (84, 'Macrothelypteris (H. Itô) Ching', 125.42, 5, 8603.61, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (85, 'Solidago sempervirens L. var. mexicana (L.) Fernald', 28.13, 1, 2608.23, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (86, 'Lichinella Nyl.', 3.32, 5, 4777.76, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (87, 'Mentzelia tiehmii N.H. Holmgren & P.K. Holmgren', 30.78, 8, 5482.41, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (88, 'Arnica fulgens Pursh', 54.85, 2, 1926.99, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (89, 'Curculigo Gaertn.', 6.28, 7, 8339.36, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (90, 'Trifolium resupinatum L.', 49.69, 1, 6660.93, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (91, 'Astragalus siliceus Barneby', 75.4, 3, 580.04, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (92, 'Eriogonum grande Greene var. rubescens (Greene) Munz', 19.85, 7, 5326.31, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (93, 'Symphyotrichum praealtum (Poir.) G.L. Nesom var. angustior (Wiegand) G.L. Nesom', 4.7, 2, 8169.02, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (94, 'Utricularia pusilla Vahl', 57.14, 2, 6589.45, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (95, 'Haplostachys bryanii Sherff', 82.52, 1, 3555.98, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (96, 'Cochlospermum religiosum (L.) Alston', 44.11, 2, 6274.0, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (97, 'Silene parishii S. Watson', 79.05, 1, 9664.28, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (98, 'Geranium caespitosum James', 102.17, 4, 1790.72, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (99, 'Solidago plumosa Small', 71.59, 4, 4260.36, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (100, 'Fimbristylis globulosa (Retz.) Kunth', 54.23, 8, 8837.5, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (101, 'Pinus contorta Douglas ex Loudon var. contorta', 33.31, 7, 4273.58, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (102, 'Agastache wrightii (Greenm.) Wooton & Standl.', 51.57, 6, 5145.38, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (103, 'Laelia rubescens Lindl.', 137.45, 6, 3865.96, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (104, 'Paspalum distichum L.', 130.45, 3, 3902.51, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (105, 'Narthecium californicum Baker', 66.74, 3, 3343.18, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (106, 'Pedilanthus tithymaloides (L.) Poit. ssp. smallii (Millsp.) Dressler', 61.91, 7, 344.79, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (107, 'Polytrichum lyallii (Mitt.) Kindb.', 17.48, 8, 422.24, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (108, 'Ilex guianensis (Aubl.) Kuntze', 88.1, 5, 4890.53, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (109, 'Perityle parryi A. Gray', 81.16, 8, 7896.28, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (110, 'Drosera brevifolia Pursh', 78.33, 7, 4383.42, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (111, 'Cheilanthes wrightii Hook.', 87.04, 1, 3620.83, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (112, 'Hordeum marinum Huds.', 67.34, 6, 7169.54, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (113, 'Brosimum utile (Kunth) Pittier', 70.2, 4, 3285.45, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (114, 'Pyrenula confoederata R.C. Harris', 13.5, 8, 427.42, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (115, 'Symplocos martinicensis Jacq.', 67.27, 1, 2430.45, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (116, 'Papillaria (Müll. Hal.) Müll. Hal.', 42.19, 9, 6619.6, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (117, 'Lecanora bicincta Ramond', 138.64, 2, 8600.66, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (118, 'Platanthera ×estesii Schrenk', 116.57, 9, 5028.76, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (119, 'Ranunculus pygmaeus Wahlenb.', 53.85, 5, 5764.22, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (120, 'Salsola kali L. ssp. pontica (Pall.) Mosyakin', 84.27, 2, 6304.33, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (121, 'Spartina pectinata Bosc ex Link', 12.12, 5, 4202.6, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (122, 'Tipuana tipu (Benth.) Kuntze', 120.47, 9, 4009.43, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (123, 'Arthonia rhoidis Zahlbr.', 65.54, 9, 5024.68, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (124, 'Carex texensis (Torr.) L.H. Bailey', 142.65, 3, 2789.24, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (125, 'Cyrtandra ×turbiniformis H. St. John & Storey (pro sp.)', 107.48, 9, 9837.76, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (126, 'Plagiobothrys nothofulvus (A. Gray) A. Gray', 139.46, 4, 6458.02, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (127, 'Delphinium lineapetalum Ewan', 45.92, 3, 5939.83, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (128, 'Echinocereus pectinatus (Scheidw.) Engelm. var. pectinatus (Scheidw.) Engelm. [excluded]', 44.07, 7, 9914.59, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (129, 'Plantago elongata Pursh ssp. pentasperma Bassett', 21.94, 5, 1067.34, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (130, 'Amorphophallus paeoniifolius (Dennst.) Nicolson', 105.82, 4, 2420.51, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (131, 'Dichanthium Willem.', 32.95, 2, 1370.56, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (132, 'Calylophus hartwegii (Benth.) P.H. Raven ssp. hartwegii', 16.22, 2, 2384.0, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (133, 'Froelichia floridana (Nutt.) Moq. var. floridana', 10.16, 1, 331.17, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (134, 'Chorizanthe membranacea Benth.', 129.78, 7, 2445.97, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (135, 'Baccharis emoryi A. Gray', 58.85, 8, 3314.82, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (136, 'Pellaea mucronata (D.C. Eaton) D.C. Eaton ssp. californica (Lemmon) Windham', 90.1, 1, 1024.86, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (137, 'Arthonia galactitella Nyl.', 64.12, 1, 7134.77, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (138, 'Crepis rubra L.', 108.13, 6, 5695.35, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (139, 'Abies lasiocarpa (Hook.) Nutt. var. arizonica (Merriam) Lemmon', 106.13, 3, 4369.58, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (140, 'Piriqueta cistoides (L.) Griseb. ssp. cistoides', 134.91, 9, 8965.65, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (141, 'Stigmaphyllon floribundum (DC.) C.E. Anderson', 30.23, 8, 411.75, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (142, 'Plectranthus verticillatus (L. f.) Druce', 126.2, 3, 459.63, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (143, 'Trifolium heldreichianum (Gibelli & Belli) Hausskn.', 13.85, 3, 7716.81, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (144, 'Allowissadula holosericea (Scheele) D.M. Bates', 143.58, 1, 2204.34, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (145, 'Bryum calobryoides Spence', 144.86, 7, 5166.71, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (146, 'Carex incurviformis Mack.', 40.38, 8, 170.61, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (147, 'Isoetes macrospora Durieu', 146.4, 7, 4356.93, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (148, 'Sphaeralcea coulteri (S. Watson) A. Gray', 80.36, 7, 6576.89, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (149, 'Sideroxylon lanuginosum Michx. ssp. albicans (Sarg.) Kartesz & Gandhi', 37.02, 3, 658.52, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (150, 'Ruellia pedunculata Torr. ex A. Gray', 69.39, 7, 2279.82, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (151, 'Allium sativum L.', 13.5, 1, 6877.99, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (152, 'Callistemon salignus (Sm.) Sweet', 28.01, 5, 534.07, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (153, 'Crumia Schof.', 61.81, 5, 6038.19, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (154, 'Solidago rugosa Mill. ssp. rugosa var. rugosa', 133.3, 1, 3370.95, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (155, 'Astragalus atratus S. Watson var. atratus', 113.52, 4, 1727.77, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (156, 'Lycium carolinianum Walter var. quadrifidum (Dunal) C.L. Hitchc.', 148.74, 1, 8904.48, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (157, 'Arabis pallidifolia Rollins', 130.15, 6, 5482.19, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (158, 'Phaeophyscia endococcina (Körb.) Moberg', 76.95, 8, 1977.73, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (159, 'Isocoma menziesii (Hook. & Arn.) G.L. Nesom var. menziesii', 14.06, 8, 5464.96, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (160, 'Albizia procera (Roxb.) Benth.', 31.29, 5, 9119.58, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (161, 'Eriogonum trichopes Torr. var. trichopes', 116.94, 9, 8691.87, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (162, 'Cakile lanceolata (Willd.) O.E. Schulz ssp. fusiformis (Greene) Rodman', 90.94, 3, 9206.99, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (163, 'Juncus supiniformis Engelm.', 105.09, 3, 737.5, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (164, 'Prosopis calingastana Burkart', 30.08, 6, 3892.03, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (165, 'Helenium flexuosum Raf.', 98.92, 9, 7062.08, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (166, 'Vitex agnus-castus L. var. agnus-castus', 65.3, 8, 4951.41, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (167, 'Symphyotrichum greatae (Parish) G.L. Nesom', 89.09, 5, 7897.67, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (168, 'Collinsonia tuberosa Michx.', 87.52, 2, 9766.04, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (169, 'Carex reznicekii Werier', 143.84, 6, 5831.14, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (170, 'Arthothelium orbilliferum (Almq.) Hasse', 82.36, 3, 32.34, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (171, 'Atriplex elegans (Moq.) D. Dietr. var. elegans', 63.26, 8, 2231.03, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (172, 'Astragalus pycnostachyus A. Gray', 136.28, 2, 8419.3, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (173, 'Lecidea olivascens Th. Fr.', 104.74, 6, 1235.01, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (174, 'Geum calthifolium Menzies ex Sm.', 132.21, 6, 3716.25, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (175, 'Monolopia congdonii (A. Gray) B.G. Baldw.', 137.87, 5, 2430.4, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (176, 'Houstonia rosea (Raf.) Terrell', 91.01, 5, 8754.04, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (177, 'Crataegus mollis Scheele', 55.15, 9, 1709.04, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (178, 'Veronica biloba L.', 94.28, 1, 1139.61, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (179, 'Eucalyptus ×mortoniana Kinney (pro sp.)', 23.83, 1, 3430.69, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (180, 'Cornus suecica L.', 143.72, 2, 8757.4, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (181, 'Pireella Cardot', 93.82, 5, 3849.65, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (182, 'Galphimia angustifolia Benth.', 46.44, 8, 6268.51, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (183, 'Tonestus microcephalus (Cronquist) G.L. Nesom & D. Morgan', 46.69, 9, 9701.46, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (184, 'Rubus apogaeus L.H. Bailey', 116.53, 3, 9693.37, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (185, 'Setaria reverchonii (Vasey) Pilg. ssp. ramiseta (Scribn.) W.E. Fox', 146.86, 1, 379.45, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (186, 'Hypnum cupressiforme Hedw. var. julaceum Brid.', 121.62, 2, 8374.24, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (187, 'Caloplaca cinnabarina (Ach.) Zahlbr.', 1.55, 2, 2269.2, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (188, 'Rosa woodsii Lindl.', 104.69, 3, 8437.14, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (189, 'Bryum hagenii Limpr.', 138.12, 4, 7500.74, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (190, 'Collema coccophorum Tuck.', 90.06, 8, 1305.64, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (191, 'Thelidium parvulum Arnold', 37.12, 3, 1569.79, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (192, 'Scabiosa palaestrina L.', 74.85, 7, 9338.74, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (193, 'Zelometeorium patulum (Hedw.) Man.', 44.61, 4, 4942.14, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (194, 'Desmodium nuttallii (Schindl.) B.G. Schub.', 111.09, 2, 7661.91, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (195, 'Cineraria saxifraga DC.', 124.8, 8, 2909.43, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (196, 'Tauschia hartwegii (A. Gray) J.F. Macbr.', 63.87, 5, 4051.6, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (197, 'Gentiana catesbaei Walter', 143.11, 5, 6387.57, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (198, 'Epilobium minutum Lindl. ex Lehm.', 101.08, 1, 9428.32, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (199, 'Bryoria cervinula Mot. ex Brodo & D. Hawksw.', 8.97, 9, 6492.69, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (200, 'Polygonum amphibium L.', 57.64, 9, 3851.74, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (201, 'Scirpus congdonii Britton', 23.06, 2, 1735.88, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (202, 'Carex ×subviridula Fernald', 139.48, 4, 6571.83, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (203, 'Dicentra formosa (Haw.) Walp. ssp. oregona (Eastw.) Munz', 122.53, 3, 3534.18, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (204, 'Juncus acutus L.', 52.47, 7, 3873.58, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (205, 'Rhizomnium glabrescens (Kindb.) T. Kop.', 89.58, 6, 2256.39, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (206, 'Eucalyptus resinifera Sm.', 26.14, 6, 6103.75, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (207, 'Astragalus collinus Douglas ex G. Don var. collinus', 50.69, 4, 3254.74, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (208, 'Phlox maculata L. ssp. pyramidalis (Sm.) Wherry', 116.81, 4, 431.8, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (209, 'Barkleyanthus salicifolius (Kunth) H. Rob. & Brettell', 69.85, 5, 7461.54, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (210, 'Calamagrostis stricta (Timm) Koeler', 96.69, 2, 3303.37, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (211, 'Fimbristylis pauciflora R. Br.', 7.38, 9, 8115.13, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (212, 'Scutellaria incana Biehler', 33.69, 3, 159.22, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (213, 'Wigandia urens (Ruiz & Pav.) Kunth var. caracasana (Kunth) D. Gibson', 144.57, 9, 8545.7, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (214, 'Symphyotrichum chilense (Nees) G.L. Nesom var. invenustum (Greene) G.L. Nesom', 130.64, 5, 2544.29, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (215, 'Tragus heptaneuron W.D. Clayton', 120.35, 3, 5031.91, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (216, 'Sedum niveum Davidson', 8.39, 5, 3323.7, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (217, 'Adenostoma sparsifolium Torr.', 62.0, 1, 7682.46, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (218, 'Lyonia rubiginosa (Pers.) G. Don var. stahlii (Urb.) W.S. Judd', 123.49, 1, 3678.45, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (219, 'Flueggea acidoton (L.) G.L. Webster', 27.14, 2, 6974.49, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (220, 'Chamaesyce celastroides (Boiss.) Croizat & O. Deg. var. stokesii (Forbes) O. Deg. & I. Deg.', 129.49, 9, 7177.35, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (221, 'Gutierrezia petradoria (S.L. Welsh & Goodrich) S.L. Welsh', 132.78, 6, 5057.4, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (222, 'Lecidella euphorea (Flörke) Hertel', 47.42, 7, 7722.32, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (223, 'Caulanthus pilosus S. Watson', 59.52, 9, 2747.18, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (224, 'Enydra Lour.', 3.12, 3, 7588.53, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (225, 'Centaurea ×psammogena G. Gáyer', 62.66, 6, 7180.38, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (226, 'Quercus ×exacta Trel.', 87.02, 4, 7036.26, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (227, 'Damasonium Hill', 138.22, 3, 1735.36, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (228, 'Carex amphibola Steud.', 7.88, 2, 3040.65, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (229, 'Homomallium incurvatum (Brid.) Loeske', 102.18, 2, 4655.94, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (230, 'Streptanthus breweri A. Gray', 55.01, 3, 7552.56, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (231, 'Brotherella Loeske ex Fleisch.', 107.39, 3, 1995.4, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (232, 'Hebeclinium macrophyllum (L.) DC.', 148.66, 1, 7204.46, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (233, 'Peperomia mauiensis Wawra', 78.86, 5, 8025.14, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (234, 'Pityopsis aspera (Shuttlw. ex Small) Small var. aspera', 31.84, 8, 5776.13, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (235, 'Hieracium triste Willd. ex Spreng. var. fulvum Hultén', 104.39, 4, 7641.18, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (236, 'Philadelphus mearnsii W.H. Evans ex Koehne', 16.73, 4, 5618.83, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (237, 'Artemisia cana Pursh ssp. viscidula (Osterh.) Beetle', 116.46, 3, 1720.78, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (238, 'Eleocharis compressa Sull. var. acutisquamata (Buckley) S.G. Sm.', 94.96, 7, 4400.73, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (239, 'Thymelaea passerina (L.) Coss. & Germ.', 133.93, 2, 1191.44, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (240, 'Oxypetalum R. Br.', 69.07, 7, 1022.08, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (241, 'Carex aperta Boott', 127.7, 3, 6080.23, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (242, 'Astragalus bernardinus M.E. Jones', 90.45, 7, 7740.99, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (243, 'Chiococca parvifolia Wullschl. ex Griseb.', 143.19, 3, 4327.4, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (244, 'Zantedeschia albomaculata (Hook.) Baill.', 60.06, 7, 4388.75, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (245, 'Penstemon hartwegii Benth.', 143.17, 9, 9413.19, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (246, 'Erpodium domingense (Spreng.) Brid. ex Müll. Hal.', 27.72, 8, 5933.85, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (247, 'Eriochloa polystachya Kunth', 15.39, 3, 2991.68, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (248, 'Schizanthus pinnatus Ruiz & Pav.', 71.56, 6, 9248.21, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (249, 'Chrysopsis godfreyi Semple', 36.96, 7, 3357.86, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (250, 'Cystopteris protrusa (Weath.) Blasdell', 148.77, 7, 865.33, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (251, 'Callistemon rigidus R. Br.', 98.87, 6, 1294.11, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (252, 'Oxalis priceae Small ssp. colorea (Small) Eiten', 137.38, 1, 7332.41, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (253, 'Potentilla cinerea Willd. ex Schlect.', 17.55, 3, 4226.48, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (254, 'Astragalus lentiginosus Douglas ex Hook. var. wilsonii (Greene) Barneby', 4.08, 2, 6870.0, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (255, 'Lagophylla minor (D.D. Keck) D.D. Keck', 98.52, 7, 2790.81, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (256, 'Coccocarpia domingensis Vain.', 37.07, 8, 4853.28, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (257, 'Costus guanaiensis Rusby var. macrostrobilus (K. Schum.) Maas', 60.91, 9, 752.15, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (258, 'Stachys rigida Nutt. ex Benth. var. rigida', 20.33, 7, 605.42, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (259, 'Calystegia subacaulis Hook. & Arn. ssp. episcopalis Brummitt', 15.73, 1, 3196.58, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (260, 'Madhuca indica J.F. Gmel.', 50.45, 9, 1997.75, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (261, 'Erigeron caespitosus Nutt.', 141.25, 2, 761.66, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (262, 'Dudleya multicaulis (Rose) Moran', 120.59, 9, 9628.4, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (263, 'Carex ×arctophila F. Nyl.', 38.38, 7, 435.34, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (264, 'Bruguiera parviflora (Roxb.) Wight & Arn. ex Griffith', 57.74, 8, 3290.0, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (265, 'Pentagramma triangularis (Kaulf.) Yatsk., Windham & E. Wollenw. ssp. maxonii (Weath.) Yatsk., Windham & E. Wollenw.', 80.59, 2, 4.42, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (266, 'Guettarda L.', 68.99, 2, 3907.86, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (267, 'Lyonothamnus A. Gray', 12.86, 1, 8608.43, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (268, 'Bromus inermis Leyss. ssp. pumpellianus (Scribn.) Wagnon var. pumpellianus (Scribn.) C.L. Hitchc.', 92.51, 3, 6661.47, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (269, 'Potamogeton ×subobtusus Hagstr.', 69.95, 7, 2308.91, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (270, 'Cyclachaena xanthiifolia (Nutt.) Fresen.', 54.07, 1, 8417.58, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (271, 'Stachys albens A. Gray', 97.82, 9, 1130.3, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (272, 'Vitis cinerea (Engelm.) Engelm. ex Millard var. baileyana (Munson) Comeaux', 21.24, 8, 9035.49, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (273, 'Cordylanthus capitatus Nutt. ex Benth.', 28.17, 1, 2734.84, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (274, 'Brodiaea santarosae T.J.Chester, W.P.Armstr. & Madore', 72.6, 7, 5878.17, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (275, 'Chamaecyparis lawsoniana (A. Murray bis) Parl.', 79.3, 4, 9207.25, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (276, 'Platanthera ×bicolor (Raf.) Luer (pro sp.)', 82.47, 3, 4784.6, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (277, 'Baltimora recta L.', 118.11, 6, 1554.79, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (278, 'Phyllanthus pentaphyllus C. Wright ex Griseb. ssp. pentaphyllus', 77.09, 2, 6974.77, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (279, 'Lomatium cous (S. Watson) J.M. Coult. & Rose', 74.26, 6, 1178.72, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (280, 'Heliconia latispatha Benth.', 71.09, 6, 8900.75, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (281, 'Solidago nemoralis Aiton var. longipetiolata (Mack. & Bush) Palmer & Steyerm.', 34.41, 1, 7396.63, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (282, 'Dalibarda repens L.', 45.87, 4, 7401.02, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (283, 'Sarea Fr.', 132.6, 3, 3455.63, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (284, 'Spergularia rubra (L.) J. Presl & C. Presl', 105.9, 7, 8263.58, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (285, 'Physaria geyeri (Hook.) A. Gray var. geyeri', 54.54, 8, 100.43, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (286, 'Hirschfeldia Moench', 13.19, 6, 5622.25, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (287, 'Agave schottii Engelm. var. schottii', 73.09, 8, 9919.17, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (288, 'Eucalyptus rudis Endl.', 136.9, 3, 6824.5, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (289, 'Lycopus uniflorus Michx.', 120.41, 2, 5239.31, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (290, '×Elyhordeum dakotense (Bowden) Bowden', 115.7, 4, 6856.63, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (291, 'Symphyotrichum drummondii (Lindl.) G.L. Nesom var. texanum (Burgess) G.L. Nesom', 70.03, 2, 4282.11, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (292, 'Bromus anomalus Rupr. ex Fourn.', 101.94, 4, 4070.02, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (293, 'Ranunculus canus Benth.', 28.82, 8, 2400.79, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (294, 'Solanum erianthum D. Don', 136.69, 5, 7891.37, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (295, 'Symphyotrichum laurentianum (Fernald) G.L. Nesom', 20.97, 7, 5992.52, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (296, 'Pseudabutilon umbellatum (L.) Fryxell', 55.93, 3, 8225.63, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (297, 'Anredera cordifolia (Ten.) Steenis', 51.3, 8, 5644.46, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (298, 'Saxifraga caespitosa L. ssp. monticola (Small) A.E. Porsild', 78.03, 7, 4841.81, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (299, 'Ophioglossum petiolatum Hook.', 100.66, 3, 9782.49, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (300, 'Ligusticum scoticum L.', 138.66, 4, 2759.95, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (301, 'Mimulus mohavensis Lemmon', 17.33, 4, 7874.17, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (302, 'Symphyotrichum greatae (Parish) G.L. Nesom', 107.68, 7, 995.46, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (303, 'Physalis L.', 127.78, 5, 2995.75, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (304, 'Silene L.', 7.35, 9, 8417.48, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (305, '×Elyhordeum Mansf. ex Zizin & Petrowa', 93.73, 1, 8892.92, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (306, 'Castilleja pilosa (S. Watson) Rydb. var. steenensis (Pennell) N.H. Holmgren', 41.69, 9, 6565.7, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (307, 'Arthonia ochrodiscodes Nyl.', 3.6, 8, 3106.31, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (308, 'Baptisia cinerea (Raf.) Fernald & B.G. Schub.', 35.02, 2, 6131.02, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (309, 'Melochia spicata (L.) Fryxell', 119.61, 8, 9659.62, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (310, 'Erigeron blochmaniae Greene', 88.63, 4, 1811.19, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (311, 'Desmodium axillare (Sw.) DC. var. acutifolium (Kuntze) Urb.', 61.1, 7, 65.62, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (312, 'Sanicula odorata (Raf.) K.M. Pryer & L.R. Phillippe', 142.4, 4, 7645.43, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (313, 'Carthamus lanatus L. ssp. creticus (L.) Holmboe', 28.19, 2, 5718.74, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (314, 'Rhodiola integrifolia Raf. ssp. neomexicana (Britton) Kartesz', 129.61, 2, 5743.78, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (315, 'Theobroma cacao L.', 22.79, 3, 6866.32, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (316, 'Gilia sinuata Douglas ex Benth.', 121.74, 6, 2773.52, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (317, 'Chelidonium majus L.', 49.67, 9, 4529.84, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (318, 'Carex debilis Michx.', 43.47, 3, 4973.99, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (319, 'Phlox richardsonii Hook. ssp. richardsonii', 97.76, 5, 647.64, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (320, 'Strigula nitidula Mont.', 131.32, 5, 4756.13, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (321, 'Drummondia Hook. ex Drumm.', 31.76, 7, 6297.14, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (322, 'Blyxa aubertii Rich.', 57.16, 9, 8084.89, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (323, 'Umbilicaria vellea (L.) Ach.', 90.03, 5, 7495.61, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (324, 'Ochrolechia groenlandica Verseghy', 26.26, 5, 9814.54, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (325, 'Heterodermia casarettiana (A. Massal.) Trevis.', 1.9, 2, 3162.3, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (326, 'Physalis mollis Nutt.', 25.62, 9, 4355.51, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (327, 'Galium obtusum Bigelow', 38.77, 2, 4362.89, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (328, 'Xyris flabelliformis Chapm.', 14.94, 5, 6152.67, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (329, 'Rubus baileyanus Britton', 77.27, 7, 5813.97, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (330, 'Carex arenaria L.', 15.63, 2, 2003.58, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (331, 'Wilkesia hobdyi H. St. John', 91.02, 1, 5890.28, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (332, 'Hemizonia kelloggii Greene', 27.42, 7, 5748.25, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (333, 'Camissonia cheiranthifolia (Hornem. ex Spreng.) Raimann ssp. cheiranthifolia', 105.85, 9, 8970.69, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (334, 'Leucojum vernum L.', 62.83, 5, 3213.77, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (335, 'Clarkia rubicunda (Lindl.) F.H. Lewis & M.E. Lewis', 86.57, 8, 9870.39, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (336, 'Anomobryum leptostomoides Schimp.', 120.72, 2, 3008.62, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (337, 'Stanleya Nutt.', 51.32, 3, 923.05, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (338, 'Philodendron consanguineum Schott', 43.91, 9, 4848.57, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (339, 'Dichanthelium dichotomum (L.) Gould var. ensifolium (Baldw. ex Elliott) Gould & C.A. Clark', 136.73, 2, 7794.67, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (340, 'Beaucarnea Lem.', 107.06, 8, 2806.95, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (341, 'Ulota obtusiuscula Müll. Hal. & Kindb.', 139.87, 3, 2035.79, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (342, 'Astragalus pattersonii A. Gray ex Brandegee', 16.44, 5, 1271.41, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (343, 'Ivesia cryptocaulis (Clokey) D.D. Keck', 56.85, 1, 1885.62, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (344, 'Terminalia bellirica (Gaertn.) Roxb.', 143.37, 1, 9184.57, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (345, 'Lathyrus ochroleucus Hook.', 118.16, 9, 4669.71, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (346, 'Lomatium attenuatum Evert', 88.76, 8, 9112.9, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (347, 'Aquilegia desolatica S.L. Welsh & N.D. Atwood', 45.36, 9, 9432.11, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (348, 'Panicum dichotomiflorum Michx.', 27.72, 4, 3263.64, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (349, 'Crocus sieberi J. Gay', 145.54, 8, 2194.63, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (350, 'Urochloa ramosa (L.) Nguyen', 88.2, 8, 6070.14, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (351, 'Draba subalpina Goodman & C.L. Hitchc.', 61.14, 4, 5763.14, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (352, 'Panax pseudoginseng Wall. ssp. pseudoginseng', 92.36, 4, 7905.86, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (353, 'Marshallia caespitosa Nutt. ex DC. var. signata Beadle & F.E. Boynt.', 34.85, 8, 3193.94, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (354, 'Lonchocarpus nicou (Aubl.) DC.', 26.04, 9, 3108.77, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (355, 'Alternanthera crucis (Moq.) Boldingh', 129.3, 8, 5863.29, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (356, 'Orobanche californica Cham. & Schltdl. ssp. californica', 101.65, 5, 228.2, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (357, 'Persea americana Mill. var. drymifolia (Schltdl. & Cham.) S.F. Blake', 42.91, 1, 445.57, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (358, 'Cranichis ricartii Ackerman', 89.69, 5, 9762.2, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (359, 'Trichodon cylindricus (Hedw.) Schimp. var. cylindricus', 33.84, 5, 4130.16, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (360, 'Diploschistes actinostomus (Ach.) Zalhbr.', 111.49, 3, 7387.86, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (361, 'Rubus alaskensis L.H. Bailey', 26.49, 6, 5349.95, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (362, 'Lupinus hillii Greene var. arizonicus (C.P. Sm.) Harmon', 1.03, 1, 6043.33, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (363, 'Zigadenus venenosus S. Watson var. gramineus (Rydb.) Walsh ex M. Peck', 62.84, 5, 470.24, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (364, 'Digitaria iburua Stapf [excluded]', 129.96, 1, 1423.92, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (365, 'Quercus ×willdenowiana (Dippel) Beissner, Schelle & Zabel (pro sp.)', 10.62, 6, 614.2, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (366, 'Xanthoparmelia neoconspersa (Gyel.) Hale', 116.23, 2, 2159.18, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (367, 'Mimulus eastwoodiae Rydb.', 40.79, 2, 4381.39, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (368, 'Ceanothus ×mendocinensis McMinn', 13.35, 6, 133.91, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (369, 'Rosa myriadenia Greene, nom. inq.', 73.7, 1, 6218.73, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (370, 'Solanum erianthum D. Don', 29.96, 5, 3322.73, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (371, 'Plantago princeps Cham. & Schltdl. var. laxiflora A. Gray', 1.0, 5, 7175.87, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (372, 'Carex ×sullivantii Boott', 120.81, 6, 898.03, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (373, 'Madia citriodora Greene', 32.78, 8, 5827.23, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (374, 'Tetramolopium humile (A. Gray) Hillebr. ssp. humile var. sublaeve Sherff', 144.28, 6, 7606.19, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (375, 'Spiraea splendens Baumann ex K. Koch var. rosea (A. Gray) Kartesz & Gandhi', 41.12, 3, 2888.63, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (376, 'Rhynchospora baldwinii A. Gray', 123.77, 6, 1838.08, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (377, 'Tanacetum bipinnatum (L.) Sch. Bip.', 38.01, 8, 5010.3, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (378, 'Agoseris ×montana Osterh. (pro sp.)', 58.29, 4, 4360.65, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (379, 'Verbesina longifolia (A. Gray) A. Gray', 116.13, 3, 220.24, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (380, 'Linum berlandieri Hook. var. filifolium (Shinners) C.M. Rogers', 82.53, 3, 9045.16, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (381, 'Epidendrum carpophorum B. Rodrigues', 138.09, 2, 1091.14, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (382, 'Aureolaria pedicularia (L.) Raf. var. austromontana Pennell', 42.62, 7, 5987.81, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (383, 'Philadelphus floridus Beadle', 78.77, 2, 6463.02, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (384, 'Fontinalis missourica Cardot', 40.2, 9, 2253.71, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (385, 'Acacia irrorata Sieber ex Spreng.', 140.92, 3, 1651.9, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (386, 'Liatris aspera Michx. var. intermedia (Lunell) Gaiser', 107.36, 9, 6283.32, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (387, 'Plagiobothrys tener (Greene) I.M. Johnst. var. subglaber I.M. Johnst.', 109.91, 4, 4319.02, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (388, 'Erigeron arenarioides (D.C. Eaton ex A. Gray) A. Gray ex Rydb.', 80.81, 6, 6025.02, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (389, 'Salix floridana Chapm.', 141.11, 9, 2197.64, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (390, 'Jarilla Rusby', 25.12, 8, 5227.35, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (391, 'Sphaeralcea fendleri A. Gray ssp. elongata Kearney', 149.62, 7, 5218.54, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (392, 'Lygodium microphyllum (Cav.) R. Br.', 23.58, 2, 4714.76, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (393, 'Camelina rumelica Velen.', 30.87, 9, 8575.21, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (394, 'Pandanus japensis Martelli', 81.9, 9, 2873.0, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (395, 'Crataegus pinnatifida Bunge var. major N.E. Br.', 64.28, 2, 9887.5, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (396, 'Stenaria nigricans (Lam.) Terrell var. gypsophila (B.L. Turner) Terrell', 135.6, 8, 8680.8, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (397, 'Pseudoleskea saviana (De Not.) Latz.', 96.11, 3, 7852.48, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (398, 'Schistidium trichodon (Brid.) Poelt', 106.24, 9, 1653.76, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (399, 'Holosteum L.', 14.9, 2, 6311.46, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (400, 'Enceliopsis argophylla (D.C. Eaton) A. Nelson', 141.52, 8, 5288.49, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (401, 'Arctostaphylos regismontana Eastw.', 132.35, 5, 1861.9, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (402, 'Cyrtandra macraei A. Gray', 77.42, 9, 5450.5, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (403, 'Echinomastus intertextus (Engelm.) Britton & Rose var. intertextus ', 41.03, 5, 4954.72, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (404, 'Isochilus R. Br.', 8.52, 5, 9563.5, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (405, 'Rinodina vegasii de Lesd.', 43.33, 2, 9649.0, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (406, 'Quercus ×subintegra (Engelm.) Trel.', 14.29, 4, 5939.64, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (407, 'Conoclinium coelestinum (L.) DC.', 88.34, 7, 723.9, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (408, 'Desmodium axillare (Sw.) DC. var. axillare', 3.66, 7, 780.79, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (409, 'Achnatherum thurberianum (Piper) Barkworth', 25.7, 7, 7596.48, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (410, 'Puccinellia hultenii Swallen', 127.56, 2, 153.6, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (411, 'Carminatia tenuiflora DC.', 106.2, 4, 4042.91, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (412, 'Pittosporum Banks ex Sol.', 111.58, 9, 2018.69, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (413, 'Plantago heterophylla Nutt.', 36.59, 2, 8639.14, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (414, 'Caltha leptosepala DC. ssp. leptosepala', 20.51, 2, 634.53, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (415, 'Penstemon pseudospectabilis M.E. Jones ssp. pseudospectabilis', 14.87, 2, 8892.03, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (416, 'Juniperus californica Carrière', 142.31, 5, 3076.23, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (417, 'Reverchonia arenaria A. Gray', 92.8, 7, 7783.57, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (418, 'Richardia scabra L.', 105.01, 4, 8101.36, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (419, 'Chamaesyce ×keyensis Small', 68.45, 7, 3552.0, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (420, 'Anaptychia palmulata (Michx.) Vain.', 38.27, 7, 721.98, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (421, 'Rhamnus serrata Humb. & Bonpl. ex Schult.', 50.05, 1, 7138.95, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (422, 'Fimbristylis autumnalis (L.) Roem. & Schult.', 21.9, 4, 1291.56, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (423, 'Acalypha neomexicana Müll. Arg.', 10.88, 8, 8871.39, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (424, 'Penstemon gairdneri Hook. var. oreganus A. Gray', 99.07, 5, 8116.63, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (425, 'Astragalus ackermanii Barneby', 38.62, 4, 2531.8, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (426, 'Lomatium simplex (Nutt.) J.F. Macbr. var. leptophyllum (Hook.) Mathias', 22.19, 9, 3027.86, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (427, 'Rhynchospora torreyana A. Gray', 61.16, 8, 9083.62, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (428, 'Rhynchosia difformis (Elliott) DC.', 62.93, 1, 2237.67, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (429, 'Asperugo procumbens L.', 118.45, 4, 8606.71, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (430, 'Rhododendron occidentale (Torr. & A. Gray) A. Gray', 95.87, 6, 6663.37, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (431, 'Sisyrinchium demissum Greene', 74.06, 4, 9603.89, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (432, 'Paspalum guenoarum Arechav.', 46.31, 2, 4646.4, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (433, 'Viola appalachiensis Henry', 81.08, 3, 5554.41, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (434, 'Eryngium creticum Lam.', 76.55, 2, 6782.65, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (435, 'Phlox nivalis Lodd. ex Sweet ssp. hentzii (Nutt.) Wherry', 82.59, 9, 2198.6, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (436, 'Andropogon brachystachyus Chapm.', 115.86, 6, 7378.05, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (437, 'Cephalaria syriaca (L.) Scrad. ex Roem. & Schult.', 64.99, 7, 2253.3, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (438, 'Verbesina lindheimeri B.L. Rob. & Greenm.', 27.09, 1, 2993.25, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (439, 'Tephrosia candida DC.', 47.89, 8, 693.98, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (440, 'Plecostachys serpyllifolia (P.J. Bergius) Hilliard & B.L. Burtt', 47.36, 8, 2896.59, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (441, 'Senna orcuttii (Britton & Rose) Irwin & Barneby', 69.07, 8, 9352.85, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (442, 'Cladonia botrytes (K. Hagen) Willd.', 37.14, 4, 4343.53, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (443, 'Lythrum portula (L.) D.A. Webb', 89.68, 3, 8442.5, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (444, 'Veratrum californicum Durand var. californicum', 112.54, 5, 2322.07, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (445, 'Elaphoglossum alatum Gaudich. var. parvisquamaeum (Skottsb.) W.R. Anderson & Crosby', 39.34, 5, 6419.08, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (446, 'Cynanchum ligulatum (Benth.) Woodson', 108.83, 6, 6251.23, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (447, 'Cryptantha hispidula Greene ex Brand', 116.34, 3, 9971.68, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (448, 'Equisetum ×litorale Kühlewein ex Rupr. (pro sp.)', 91.63, 6, 5890.01, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (449, 'Epilobium montanum L.', 106.15, 9, 5522.38, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (450, 'Stenorrhynchos lanceolatum (Aubl.) Rich.', 80.39, 6, 7435.24, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (451, 'Schoenoplectus torreyi (Olney) Palla', 7.91, 7, 1565.59, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (452, 'Sphenosciadium capitellatum A. Gray', 64.07, 7, 226.01, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (453, 'Hygrohypnum norvegicum (Schimp.) Amann', 84.29, 2, 1245.76, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (454, 'Stapelia L.', 132.16, 1, 2497.61, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (455, 'Lepidium virginicum L.', 89.11, 7, 6469.05, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (456, 'Spilanthes urens Jacq.', 76.82, 8, 4942.95, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (457, 'Eleocharis acicularis (L.) Roem. & Schult. var. porcata S.G. Sm.', 9.35, 3, 6267.59, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (458, 'Stegnosperma Benth.', 6.98, 9, 3777.63, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (459, 'Melanelia stygia (L.) Essl.', 87.36, 5, 2333.93, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (460, 'Festuca ligulata Swallen', 42.51, 2, 5321.87, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (461, 'Drosera ×linglica Kusakabe ex R. Gauthier & Gervais', 114.24, 7, 1548.25, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (462, 'Cephalotaxus Siebold & Zucc. ex Endl.', 56.84, 7, 1941.03, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (463, 'Trichocereus (A. Berger) Riccob.', 110.5, 6, 6420.39, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (464, 'Cyrto-hypnum involvens (Hedw.) W.R. Buck & H.A. Crum', 142.38, 5, 2226.74, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (465, 'Populus ×parryi Sarg.', 21.58, 4, 2722.46, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (466, 'Cylindropuntia ×vivipara (Rose) F.M. Knuth (pro sp.)', 28.63, 2, 409.12, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (467, 'Paspalum notatum Flueggé var. latiflorum J. Döll', 125.53, 9, 9648.85, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (468, 'Cladonia crispata (Ach.) Flotow', 51.59, 5, 5245.07, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (469, 'Hypogymnia krogiae Ohlsson', 103.67, 6, 5028.76, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (470, 'Solidago speciosa Nutt. var. jejunifolia (Steele) Cronquist', 30.5, 2, 1255.68, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (471, 'Hygroamblystegium tenax (Hedw.) Jenn. var. spinifolium (Schimp.) Jenn.', 13.3, 7, 3599.35, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (472, 'Spiraea japonica L. f. var. fortunei (Planch.) Rehder', 20.49, 2, 4759.76, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (473, 'Lasallia pensylvanica (Hoffm.) Llano', 72.66, 6, 8482.03, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (474, 'Oxytropis lambertii Pursh var. bigelovii A. Gray', 30.37, 6, 5987.27, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (475, 'Tridens buckleyanus (L.H. Dewey) Nash', 92.62, 7, 7820.93, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (476, 'Bahia absinthifolia Benth. var. dealbata (A. Gray) A. Gray', 101.25, 2, 7271.68, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (477, 'Justicia borinquensis Britton', 73.61, 6, 7465.35, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (478, 'Claytonia cordifolia S. Watson', 105.05, 3, 264.53, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (479, 'Pinus pinea L.', 126.4, 9, 2129.42, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (480, 'Lobelia robusta Graham var. robusta Graham [excluded]', 69.94, 5, 361.18, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (481, 'Buddleja racemosa Torr. ssp. racemosa', 133.78, 6, 6707.05, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (482, 'Pseudoleskea julacea (Besch. & Cardot) H.A. Crum, Steere & L.E. Anderson', 75.87, 4, 4731.27, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (483, 'Minuartia patula (Michx.) Mattf.', 66.62, 4, 6955.15, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (484, 'Argemone albiflora Hornem.', 61.53, 9, 6049.43, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (485, 'Persea americana Mill.', 88.4, 4, 8695.06, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (486, 'Juncus bryoides F.J. Herm.', 26.85, 8, 3009.27, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (487, 'Carex purpurifera Mack.', 27.62, 1, 3818.87, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (488, 'Ivesia webberi A. Gray', 54.46, 9, 4443.33, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (489, 'Gutierrezia texana (DC.) Torr. & A. Gray var. texana', 65.8, 8, 7708.78, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (490, 'Celtis bungeana Blume', 20.92, 8, 4790.72, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (491, 'Coreopsis palmata Nutt.', 95.07, 8, 8058.97, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (492, 'Trapelia mooreana (Carroll) P. James', 117.85, 6, 9210.08, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (493, 'Lasthenia microglossa (DC.) Greene', 1.33, 3, 5877.44, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (494, 'Eremalche rotundifolia (A. Gray) Greene', 134.8, 6, 3171.47, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (495, 'Agalinis calycina Pennell', 148.75, 1, 4292.35, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (496, 'Botrychium rugulosum W.H. Wagner', 130.42, 7, 4966.12, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (497, 'Lomatium cusickii (S. Watson) J.M. Coult. & Rose', 2.48, 1, 9501.42, false);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (498, 'Platanthera blephariglottis (Willd.) Lindl.', 29.13, 2, 7403.81, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (499, 'Atriplex fruticulosa Jeps.', 4.26, 6, 5064.74, true);
insert into Food (FoodId, FoodName, FoodPrice, CategoryId, Calories, Availability) values (500, 'Draba helleriana Greene var. bifurcata C.L. Hitchc.', 81.04, 7, 895.1, false);
