insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (1, 'OXYGEN', 3, 296, 453);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (2, 'Berkley and Jensen Aspirin', 42, 63, 117);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (3, 'BP Wash Acne Treatment Pack', 36, 350, 83);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (4, 'Minocycline Hydrochloride', 24, 21, 201);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (5, 'Nicomide', 32, 107, 451);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (6, 'Metformin Hydrochloride', 26, 341, 57);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (7, 'Bac Off', 37, 338, 464);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (8, 'Amitriptyline Hydrochloride', 27, 121, 71);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (9, 'Atenolol', 42, 309, 351);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (10, 'Rhodotorula mucilaginosa', 49, 280, 478);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (11, 'IMITREX', 28, 432, 407);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (12, 'Menstrual - PMS', 43, 23, 403);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (13, 'Nadolol', 27, 491, 457);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (14, 'HERBAL DAHUIN BEAUTY', 49, 314, 25);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (15, 'Head Congestion Cold Relief', 47, 40, 116);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (16, 'careone pain relief', 23, 320, 369);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (17, 'Bupropion Hydrochloride', 19, 71, 421);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (18, 'Penicilium chrysogenum', 23, 5, 314);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (19, 'Trelstar', 3, 103, 443);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (20, 'Acetylcysteine', 30, 202, 201);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (21, 'Hongocura', 9, 446, 467);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (22, 'Spironolactone', 3, 101, 236);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (23, 'Vanilla Bean', 4, 214, 124);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (24, 'Ciprofloxacin', 49, 48, 428);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (25, 'Vinorelbine', 48, 406, 261);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (26, 'Gabapentin', 5, 211, 181);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (27, 'Metformin Hydrochloride', 14, 429, 384);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (28, 'Midodrine HCl', 30, 472, 149);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (29, 'Minral Oil', 3, 82, 11);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (30, 'Maximum Strength One Step Wart Remover Strips', 44, 209, 130);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (31, 'SuperSmile Professional', 16, 401, 271);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (32, 'Olanzapine', 6, 63, 345);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (33, 'Allopurinol', 1, 271, 96);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (34, 'Infants Ibuprofen', 6, 435, 323);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (35, 'Clindamycin', 29, 295, 309);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (36, 'Midazolam Hydrochloride', 23, 490, 173);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (37, 'Sodium Polystyrene Sulfonate', 30, 310, 17);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (38, 'Absorbine Jr.', 13, 4, 400);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (39, 'Darby', 26, 229, 496);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (40, 'Anti-Itch Extra Strength', 5, 165, 500);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (41, 'Atenolol', 46, 57, 208);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (42, 'Sugar Maple', 42, 284, 431);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (43, 'Paroxetine', 29, 98, 66);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (44, 'SIMPLY RIGHT BODY CARE', 17, 81, 50);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (45, 'Badger Unscented SPF 30 Sunscreen', 16, 181, 252);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (46, 'Mucinex', 13, 31, 396);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (47, 'Equisetum Silicea', 4, 283, 32);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (48, 'HAND SANITIZING', 30, 191, 56);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (49, 'Rizatriptan', 28, 164, 370);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (50, 'Ocudox', 15, 406, 136);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (51, 'CVS Pharmacy', 14, 99, 468);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (52, 'Hydrochlorothiazide', 37, 436, 363);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (53, 'Arth Arrest', 22, 203, 448);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (54, 'Oxygen', 29, 124, 118);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (55, 'Risperidone', 18, 437, 112);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (56, 'Ipratropium Bromide', 47, 370, 488);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (57, 'Morphine Sulfate', 38, 448, 466);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (58, 'INSTA-CHAR SORBITOL', 48, 367, 122);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (59, 'adult tussin cough', 3, 342, 99);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (60, 'Multi-Vitamin Fluoride Drops', 34, 185, 247);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (61, 'Care One Cold Multi Symptom', 30, 364, 482);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (62, 'SOFT AND PRECIOUS NURSERY', 15, 398, 288);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (63, 'Ceramide Plump Perfect Lip Moisture SPF 30', 34, 475, 227);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (64, 'Myoflex Pain Relieving Cream', 24, 199, 487);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (65, 'Allergena', 16, 57, 186);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (66, 'Dibasic Sodium Phosphate, Monobasic Potassium Phosphate and Monobasic Sodium Phosphate', 14, 302, 483);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (67, 'Multi-Vitamin Fluoride Drops', 28, 269, 392);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (68, 'LEVOTHYROXINE SODIUM', 48, 440, 346);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (69, 'allergy relief eye', 19, 487, 407);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (70, 'Tolterodine Tartrate Extended Release', 17, 460, 203);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (71, 'nicotine polacrilex', 1, 185, 332);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (72, 'Benztropine Mesylate', 22, 255, 32);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (73, 'Fentanyl', 44, 208, 209);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (74, 'health mart nasal decongestant pe', 39, 347, 82);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (75, 'Pollens - Trees, Cedar, Red Juniperus virginiana', 6, 469, 125);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (76, 'FORTAMET', 26, 489, 286);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (77, 'Rhus Aconitum', 17, 141, 104);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (78, 'Obao Men Audaz', 46, 121, 111);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (79, 'Childrens Pain Relief', 10, 266, 351);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (80, 'Doxycycline Hyclate', 2, 119, 373);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (81, 'Topcare Pain Relief', 33, 193, 464);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (82, 'Prednisone', 31, 85, 108);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (83, 'The Fresh Market Hand Sanitizer With Moisturizers Aloe And Vitamin E', 32, 76, 51);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (84, 'Buspirone Hydrochloride', 35, 137, 261);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (85, 'Mucus Relief D', 12, 122, 215);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (86, 'Topcare Pain Relief', 14, 429, 481);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (87, 'Cyclobenzaprine Hydrochloride', 17, 331, 226);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (88, 'Buspirone Hydrochloride', 36, 350, 273);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (89, 'Epsom Salt', 5, 228, 386);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (90, 'Vancomycin Hydrochloride', 15, 466, 468);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (91, 'CitraNatal Harmony', 13, 59, 308);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (92, 'Dicyclomine', 15, 116, 79);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (93, 'COLGATE SPARKLING WHITE CINNAMINT', 19, 354, 410);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (94, 'Daytime Sinus Congestion And Pain', 39, 103, 341);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (95, 'SENOKOT-S', 8, 119, 245);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (96, 'LEVOXYL', 7, 184, 242);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (97, 'Ketorolac Tromethamine', 30, 70, 240);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (98, 'Senna-Lax', 9, 125, 355);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (99, 'Finacea', 21, 387, 205);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (100, 'Ketorolac Tromethamine', 38, 72, 44);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (101, 'Ibuprofen', 40, 173, 448);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (102, 'Acetaminophen', 23, 209, 239);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (103, 'Fentanyl Citrate, Bupivacaine HCl', 22, 445, 305);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (104, 'LISINOPRIL', 17, 393, 312);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (105, 'Zolpidem Tartrate', 1, 4, 492);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (106, 'Lip Balm SPF 15', 48, 250, 430);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (107, 'FLUOXETINE', 3, 455, 62);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (108, 'Nicotine Polacrilex', 41, 319, 41);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (109, 'Glyburide and Metformin Hydrochloride', 37, 146, 303);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (110, 'Methazolamide', 23, 206, 71);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (111, 'Earths Best Mineral Sunscreen Broad Spectrum SPF30', 9, 296, 13);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (112, 'Alendronate Sodium', 2, 401, 147);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (113, 'RICHENNAPHARM', 23, 25, 316);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (114, 'CD HydraLife BB Eye Creme Enhancing Sunscreen Eye Illuminator Luminous Beige Broad Spectrum SPF 20', 2, 5, 104);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (115, 'FresHands', 24, 261, 422);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (116, 'Diazepam', 23, 271, 19);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (117, 'Olanzapine', 40, 458, 418);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (118, 'Pacnex', 18, 401, 337);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (119, 'Topiramate', 49, 94, 456);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (120, 'Pioglitazone HCL and Metformin HCL', 34, 15, 131);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (121, 'Renotox', 29, 398, 142);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (122, 'Ecolab', 15, 390, 14);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (123, 'Tolterodine Tartrate Extended Release', 21, 294, 446);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (124, 'TRUFFLE EX WRINKLE SLEEPING MASK', 35, 91, 226);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (125, 'Humco Mineral Oil Heavy', 22, 375, 164);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (126, 'Everyday Clean', 37, 479, 457);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (127, 'Prialt', 24, 31, 182);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (128, 'Migraine Headache Therapy', 32, 385, 46);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (129, 'Hemorrhoidal', 47, 53, 46);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (130, 'Neutrogena Healthy Skin Firming', 24, 94, 62);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (131, 'Cisplatin', 49, 17, 402);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (132, 'Quality Choice Nighttime Cold and Flu', 45, 318, 409);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (133, 'levocetirizine dihydrochloride', 14, 125, 411);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (134, 'Amantadine Hydrochloride', 42, 29, 159);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (135, 'diltiazem hydrochloride', 17, 368, 124);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (136, 'Mineral Oil', 8, 124, 395);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (137, 'DANDRUFF SHAMPOO', 3, 393, 429);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (138, 'Ofloxacin', 23, 255, 23);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (139, 'Naproxen', 39, 402, 4);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (140, 'Levofloxacin', 21, 187, 421);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (141, 'Premarin', 40, 485, 480);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (142, 'Bodycology', 14, 95, 238);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (143, 'Duloxetine', 43, 30, 94);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (144, 'Antibacterial Hand', 44, 125, 179);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (145, 'Jelly Bean Antibacterial Hand', 32, 270, 173);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (146, 'Pepper Tree Pollen', 25, 448, 332);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (147, 'Travel Remedy', 25, 202, 471);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (148, 'Glyburide and Metformin', 42, 219, 52);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (149, 'NICOTROL', 16, 115, 18);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (150, 'Tilia Fe', 29, 20, 432);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (151, 'LEVOFLOXACIN', 10, 57, 162);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (152, 'Cyclobenzaprine Hydrochloride', 43, 272, 7);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (153, 'ULTRACIN', 36, 121, 434);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (154, 'METOPROLOL SUCCINATE', 15, 153, 93);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (155, 'Etomidate', 38, 185, 336);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (156, 'Aspirin', 46, 446, 420);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (157, 'KETOROLAC TROMETHAMINE', 16, 403, 423);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (158, 'Rexall Pain Relief', 41, 352, 92);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (159, 'Amnesteem', 1, 141, 293);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (160, 'Oxcarbazepine', 1, 244, 16);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (161, 'Levofloxacin', 46, 116, 224);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (162, 'Conazol', 34, 278, 88);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (163, 'skin effects Brightening Day SPF 50', 8, 90, 167);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (164, 'BestHealth Cherry', 3, 490, 155);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (165, 'Baby Wipes with Allantoin', 9, 184, 95);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (166, 'Dead Down Wind ScentPrevent', 36, 254, 86);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (167, 'Caduet', 22, 49, 476);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (168, 'Myorisan', 10, 421, 89);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (169, 'Dexpanthenol', 28, 31, 120);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (170, 'Ibuprofen', 49, 473, 133);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (171, 'SkinCeuticals Physical UV Defense Broad Spectrum SPF 30 Sunscreen', 31, 332, 174);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (172, 'NIGHTTIME SLEEP AID', 2, 496, 346);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (173, 'LANEIGE SATIN FINISH TWIN PACT NO. 31', 4, 388, 184);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (174, 'Tolazamide', 19, 398, 165);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (175, 'Clonidine Hydrochloride', 20, 189, 323);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (176, 'Rite Aid', 14, 51, 237);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (177, 'Lyrica', 16, 74, 190);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (178, 'Advil PM', 9, 384, 162);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (179, 'Nite Aid Sleep Aid', 18, 159, 264);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (180, 'Hydrogen Peroxide', 32, 117, 470);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (181, 'topiramate', 23, 58, 499);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (182, 'Home Sense Ultra Green Apple Scent', 26, 145, 383);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (183, 'nighttime cold flu relief', 30, 376, 234);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (184, 'Zicam', 45, 299, 125);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (185, 'Island Breeze Antibacterial Foaming Hand Wash', 7, 432, 221);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (186, 'SINGULAIR', 35, 352, 380);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (187, 'Greasewood', 37, 41, 89);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (188, 'Epicoccum nigrum', 10, 112, 277);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (189, 'Childrens MOTRIN', 15, 402, 329);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (190, 'ALZ HP', 31, 473, 397);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (191, '7 Select Childrens Allergy Relief', 27, 353, 19);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (192, 'PURELL Advanced Hand Sanitizer Holiday Spice', 13, 419, 92);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (193, 'Midodrine Hydrochloride', 27, 233, 126);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (194, 'Valsartan and Hydrochlorothiazide', 3, 133, 293);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (195, 'Harmon Face Values Daily Facial', 27, 315, 145);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (196, 'BareMinerals Dark Matte', 50, 410, 250);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (197, 'ck one 3-in-1 face makeup', 6, 348, 487);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (198, 'Telmisartan', 39, 129, 479);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (199, 'Cepacol Sensations', 12, 135, 120);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (200, 'Quinapril Hydrochloride', 25, 267, 474);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (201, 'Pollens - Trees, Tree of Heaven Ailanthus altissima', 30, 339, 74);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (202, 'METHOCARBAMOL', 42, 332, 248);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (203, 'Piroxicam', 13, 220, 250);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (204, 'Sodium Chloride', 43, 485, 148);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (205, 'Tricode', 41, 206, 357);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (206, 'Juxtapid', 11, 485, 69);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (207, 'AMARANTHUS TUBERCULATUS POLLEN', 25, 149, 229);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (208, 'junior strength acetaminophen', 34, 419, 414);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (209, 'MIDODRINE HYDROCHLORIDE', 49, 495, 434);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (210, 'Black Walnut', 32, 190, 419);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (211, 'Doxycycline Hyclate', 32, 131, 402);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (212, 'Diabetic Tussin DM', 24, 105, 458);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (213, 'Lovenox', 11, 269, 55);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (214, 'Nighttime Cold and Flu Relief Therapy', 23, 363, 134);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (215, 'Clindamycin Hydrochloride', 44, 148, 468);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (216, 'WHP Be gone Head Cold', 45, 283, 343);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (217, 'PredniSONE', 40, 336, 138);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (218, 'Etodolac', 31, 134, 360);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (219, 'Manefit Bling Bling Whitening Platinum Hydrogel Mask', 8, 449, 207);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (220, 'Topiclear Xtra lemon beauty', 28, 252, 331);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (221, 'Amnesteem', 15, 468, 13);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (222, 'Ropinirole', 24, 458, 401);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (223, 'cool heat', 11, 385, 76);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (224, 'Qsymia', 21, 57, 177);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (225, 'Cilostazol', 40, 396, 283);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (226, 'Nasal Decongestant PE', 7, 223, 429);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (227, 'Gas Relief', 32, 71, 391);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (228, 'Norco', 9, 18, 325);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (229, 'Psoriasis', 16, 168, 217);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (230, 'Warfarin Sodium', 44, 203, 158);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (231, 'FAMILY WELLNESS MEDICATED COOLING PADS', 6, 50, 425);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (232, 'RISPERIDONE', 12, 11, 354);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (233, 'Sinus and Allergy', 45, 166, 402);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (234, 'California Black Oak', 8, 241, 275);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (235, 'Cetirizine Hydrochloride', 16, 108, 493);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (236, 'GEMCITABINE', 2, 123, 248);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (237, 'Deb Med Antimicrobial Foaming Hand Wash Fresh Grapefruit', 46, 174, 500);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (238, 'SUPERDEFENSE DAILY DEFENSE MOISTURIZER BROAD SPECTRUM SPF20 (COMBINATION OILY - OILY)', 49, 454, 388);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (239, 'ARNICA MONTANA', 31, 23, 84);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (240, 'PF FOAMING ANTI-BACTERIAL HAND SANITIZING', 16, 162, 4);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (241, 'clear days ahead', 43, 33, 206);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (242, 'SKIN CAVIAR CONCEALER FOUNDATION SUNSCREEN SPF 15 - Creme Peche', 22, 500, 284);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (243, 'Cardizem', 26, 83, 45);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (244, 'CLARINS BB Skin Perfecting Cream SPF 25 Tint 00', 13, 407, 158);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (245, 'Extra Strength Headache Formula', 31, 429, 196);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (246, 'Xopenex', 22, 36, 423);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (247, 'Diltiazem Hydrochloride Extended Release', 35, 452, 480);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (248, 'ARNICA MONTANA (WHOLE PLANT)', 40, 194, 317);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (249, 'Ritussin Expectorant', 6, 328, 68);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (250, 'Neutrogena Oil Free Acne Wash', 31, 286, 231);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (251, 'CD DIORSKIN NUDE SKIN-GLOWING MAKEUP SUNSCREEN BROAD SPECTRUM SPF 15 040 Honey Beige', 36, 61, 462);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (252, 'Azulfidine', 33, 275, 157);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (253, 'Lidocaine Hydrochloride and Epinephrine Bitartrate', 4, 454, 230);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (254, 'childrens acetaminophen melts', 35, 34, 163);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (255, 'Childrens Ibuprofen', 40, 385, 327);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (256, 'Levothyroxine Sodium', 30, 450, 472);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (257, 'ORENCIA', 8, 239, 176);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (258, 'Mucinex', 37, 143, 351);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (259, 'GINSENG KIANPI PIL', 50, 267, 223);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (260, 'Urea', 22, 332, 147);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (261, 'Advanced Arnica', 10, 166, 451);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (262, 'ONDANSETRON', 47, 442, 235);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (263, 'Formula 3 Cough Syrup', 40, 266, 413);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (264, 'Homeopathic Sciatica Formula', 33, 401, 219);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (265, 'ziprasidone hydrochloride', 20, 165, 5);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (266, 'LACTULOSE', 26, 451, 361);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (267, 'Chelidonium Curcuma', 4, 351, 164);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (268, 'Pain Reliever', 34, 111, 279);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (269, 'Ultram ER', 18, 278, 68);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (270, 'Allergy Relief', 34, 349, 146);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (271, 'Naprosyn', 48, 414, 207);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (272, 'Sunmark Nasal', 9, 247, 495);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (273, 'Crestor', 30, 367, 2);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (274, 'Montelukast Sodium', 15, 450, 72);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (275, 'HYDROCODONE BIT/APAP', 37, 276, 254);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (276, 'Burweed Marsh Elder', 20, 113, 253);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (277, 'I-MAX LIGHTENING 5', 31, 387, 97);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (278, 'TRAMADOL HYDROCHLORIDE', 12, 279, 497);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (279, 'VAQTA', 30, 304, 124);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (280, 'Major Oral Pain Relief', 36, 234, 42);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (281, 'Hydrochlorothiazide', 4, 427, 395);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (282, 'Warfarin Sodium', 1, 485, 494);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (283, 'Potassium Chloride in Dextrose and Sodium Chloride', 11, 22, 257);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (284, 'PrandiMet', 12, 245, 242);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (285, 'PANADOL', 49, 133, 489);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (286, 'Daytime Nighttime Cold Flu Relief', 17, 312, 10);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (287, 'AMERICAN BEECH POLLEN', 34, 156, 490);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (288, 'Urelle', 24, 181, 483);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (289, 'Poverty Weed', 31, 127, 441);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (290, 'QUALITY CHOICE LUBRICANT TEARS EYE', 18, 184, 112);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (291, 'Quetiapine Fumarate', 22, 372, 386);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (292, 'Leader', 27, 483, 40);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (293, 'Fentanyl', 28, 84, 397);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (294, 'EXCEDRIN', 38, 56, 498);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (295, 'Lysol', 45, 192, 273);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (296, 'Temozolomide', 6, 180, 288);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (297, 'BENZTROPINE MESYLATE', 8, 174, 351);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (298, 'REVITALIZING C SERUM', 9, 341, 450);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (299, 'HYLENEX Recombinant', 14, 199, 32);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (300, 'Gourmet Kitchen Regenerating Anti-Bacterial', 6, 284, 318);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (301, 'Progena', 39, 226, 355);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (302, 'Petrolatum', 43, 54, 233);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (303, 'Regular Strength Enteric coated aspirin', 13, 168, 56);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (304, 'Pyrocaine Burn', 45, 452, 393);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (305, 'LOreal Paris Men Expert Comfort Max Hydra Energetic After Shave Balm Broad Spectrum SPF 15 Sunscreen', 1, 47, 196);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (306, 'galantamine hydrobromide', 8, 440, 360);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (307, 'Oxygen', 43, 296, 322);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (308, 'Direct Safety Aspirin', 15, 401, 99);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (309, 'UV LOCK ULTRA MILK SUN', 23, 208, 279);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (310, 'Synalar TS', 16, 380, 198);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (311, 'Banana Boat Baby Sin Lagrimas SPF 50 Pump', 34, 32, 58);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (312, 'Sulindac', 10, 396, 79);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (313, 'Ondansetron', 49, 367, 261);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (314, 'Hyperlyte', 10, 51, 349);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (315, 'Cilostazol', 31, 69, 284);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (316, 'FEIBA', 19, 13, 421);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (317, 'Pecgen DMX', 27, 25, 232);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (318, 'Medline Alcohol Prep', 34, 208, 122);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (319, 'Rhizopus oryzae', 12, 471, 455);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (320, 'CHENOPODIUM ALBUM POLLEN', 46, 265, 53);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (321, 'good sense pain relief', 15, 299, 164);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (322, 'Mixed Vespid hymenoptera venom Venomil Maintenance', 25, 333, 247);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (323, 'pain and fever', 5, 82, 363);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (324, 'END-ZIT', 29, 219, 470);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (325, 'VANOXIDE', 23, 292, 310);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (326, 'Family Wellness', 18, 487, 152);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (327, 'Fluocinonide', 50, 205, 47);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (328, 'Isosorbide Dinitrate', 13, 471, 164);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (329, 'MIDAZOLAM', 46, 80, 430);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (330, 'Amitriptyline Hydrochloride', 17, 86, 17);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (331, 'Ferric Citrate', 36, 349, 320);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (332, 'Ramipril', 33, 89, 308);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (333, 'Ziprasidone Hydrochloride', 21, 177, 454);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (334, 'povidine iodine', 43, 275, 319);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (335, 'ALTERNARIA TENUIS', 35, 258, 123);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (336, 'Fentanyl', 28, 425, 88);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (337, 'Lil Drug Store Pain Relief', 45, 358, 371);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (338, 'Dock/Sorrel Mixture', 18, 88, 335);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (339, 'pain relief', 16, 228, 452);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (340, 'Bupropion Hydrochloride', 6, 81, 83);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (341, 'Nasal Relief', 12, 101, 266);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (342, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 23, 253, 241);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (343, 'KLEENEX Antibacterial Clear Skin Cleanser', 5, 275, 339);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (344, 'Diovan', 44, 87, 24);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (345, 'Wal-dryl Itch Relief', 45, 105, 90);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (346, 'Scab Ease Itch Relief', 41, 403, 491);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (347, 'Gilphex TR', 21, 267, 267);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (348, 'Nadolol', 12, 438, 1);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (349, 'Golden Deep Foundation SPF 15', 23, 97, 385);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (350, 'IMODIUM', 49, 365, 493);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (351, 'LEVAQUIN', 3, 410, 473);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (352, 'Childrens Acetaminophen', 1, 393, 324);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (353, 'LEXIVA', 41, 68, 430);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (354, 'everyone Hand Sanitizer', 11, 300, 13);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (355, 'Amoxicillin and Clavulanate Potassium', 29, 168, 44);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (356, 'Tazza', 26, 51, 275);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (357, 'Amoxicillin', 8, 489, 32);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (358, 'GFA First Aid', 8, 237, 226);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (359, 'Mupirocin', 36, 141, 55);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (360, 'Zenchent FE', 33, 428, 369);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (361, 'health mart nasal decongestant pe', 17, 407, 23);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (362, 'Neutrogena Wet Skin Kids Beach and Pool', 4, 281, 467);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (363, 'Complete Beauty', 46, 126, 281);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (364, 'Alba Sunblock Mineral FF SPF 30', 27, 322, 431);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (365, 'HydrALAZINE Hydrochloride', 25, 386, 41);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (366, 'Periodontium Quartz Special Order', 33, 44, 148);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (367, 'Benazepril Hydrochloride', 50, 410, 20);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (368, 'Meclizine Hydrochloride', 20, 439, 99);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (369, 'Resinol', 21, 236, 207);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (370, 'Hand Sanitizer', 33, 391, 162);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (371, 'Duloxetine', 46, 48, 417);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (372, 'Blackhead Clearing Scrub', 45, 11, 10);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (373, 'Leucovorin Calcium', 1, 87, 498);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (374, 'Foot Saver', 3, 62, 220);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (375, 'Famotidine', 4, 90, 36);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (376, 'ACTONEL', 45, 470, 106);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (377, 'DiorSkin Nude 070 Dark Brown', 44, 23, 29);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (378, 'Simvastatin', 3, 86, 197);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (379, 'Omeprazole', 20, 155, 442);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (380, 'SHISEIDO RADIANT LIFTING FOUNDATION', 8, 73, 279);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (381, 'Borba Age Defying', 10, 98, 184);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (382, 'Clindamycin hydrochloride', 21, 333, 14);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (383, 'Ondansetron', 47, 107, 23);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (384, 'Etomidate', 45, 174, 213);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (385, 'JASMINE TEA AND BASIL ANTIBACTERIAL HAND SP', 33, 85, 308);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (386, 'Sunmark Loratadine', 1, 353, 369);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (387, 'Sumatriptan', 23, 356, 139);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (388, 'Paser', 16, 141, 159);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (389, 'Sure Antiperspirant Deodorant Unscented', 2, 395, 97);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (390, 'Moexipril Hydrochloride and Hydrochlorothiazide', 3, 445, 496);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (391, 'Gas Relief', 6, 370, 250);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (392, 'Metformin Hydrochloride', 16, 156, 99);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (393, 'Purse Essentials hand sanitizer Anti-Bacterial Hand', 17, 75, 467);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (394, 'IMODIUM', 11, 272, 202);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (395, 'EXTENDED PHENYTOIN SODIUM', 32, 29, 342);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (396, 'Galantamine', 47, 495, 444);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (397, 'Diltiazem Hydrochloride', 1, 240, 171);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (398, 'Good Neighbor Pharmacy Nicotine', 40, 491, 66);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (399, 'Nu Skin Nu Colour', 23, 480, 237);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (400, 'SEROQUEL', 21, 167, 292);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (401, 'Caffeine Citrate', 14, 90, 472);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (402, 'Equaline ibuprofen', 50, 267, 363);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (403, 'Mi-Omega NF', 16, 417, 315);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (404, 'Glipizide and Metformin Hydrochloride', 11, 151, 377);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (405, 'Motion-Time', 21, 119, 280);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (406, 'PanOxyl', 19, 70, 221);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (407, 'NAVI MAXON Sirin Doctor', 42, 90, 335);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (408, 'ibuprofen cold and sinus', 43, 171, 453);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (409, 'Fluoxetine', 3, 6, 439);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (410, 'ESIKA', 22, 298, 309);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (411, 'Loperamide Hydrochloride', 26, 31, 8);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (412, 'Camphor, Menthol', 2, 39, 320);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (413, 'HYDROCORTISONE', 45, 243, 288);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (414, 'leflunomide', 13, 398, 486);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (415, 'Haloperidol Decanoate', 35, 21, 276);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (416, 'Ice External Analgesic', 50, 442, 428);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (417, 'HYDROXYZINE HYDROCHLORIDE', 8, 466, 340);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (418, 'levofloxacin', 33, 72, 28);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (419, 'Dog Fennel', 22, 300, 220);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (420, 'Daily Moisturizing', 48, 444, 334);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (421, 'Natures Choice Vitamins A and D', 44, 8, 393);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (422, 'Tokyo Hand Sanitizer Vanilla Scent', 16, 474, 143);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (423, 'Vital Weight Loss', 24, 9, 254);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (424, 'Coppertone', 40, 354, 158);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (425, 'SOLU-MEDROL', 14, 491, 165);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (426, 'Bupivacaine Hydrochloride and Epinephrine', 11, 126, 300);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (427, 'Haemonetics Anticoagulant Citrate Phosphate Double Dextrose Solution (CP2D)', 21, 338, 292);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (428, 'Low Sugar Cherry Flavor Fishermans Friend Menthol Cough Suppressant', 24, 172, 385);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (429, 'Animal Allergens, Feather Mix', 29, 231, 230);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (430, 'Medistik', 33, 386, 174);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (431, 'ApexiCon', 28, 176, 485);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (432, 'Hypertensolol', 15, 123, 301);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (433, 'JUNIPERUS ASHEI POLLEN', 45, 111, 24);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (434, 'ACEPHEN', 41, 211, 437);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (435, 'H-E-B Dead Sea Organics Protect and Perfect Day Broad Spectrum SPF15', 9, 148, 231);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (436, 'Lorazepam', 9, 374, 189);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (437, 'Psoriasin', 39, 363, 23);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (438, 'PURELL Instant Hand Sanitizer Foam (ETHYL ALCOHOL)', 12, 81, 464);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (439, 'Methylene Blue', 13, 18, 164);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (440, 'Propranolol Hydrochloride', 30, 47, 201);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (441, 'potassium chloride', 33, 310, 153);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (442, 'Niaspan', 11, 399, 373);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (443, 'Heparin Lock Flush', 9, 343, 99);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (444, 'Torsemide', 47, 281, 176);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (445, 'Mackerel', 9, 439, 197);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (446, 'Levalbuterol', 39, 310, 271);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (447, 'NANO SILVER TOOTHPASTE', 34, 349, 104);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (448, 'Lidocaine Hydrochloride and Epinephrine', 13, 330, 75);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (449, 'Lamotrigine', 12, 41, 80);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (450, 'HaliTonic', 24, 402, 220);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (451, 'Tamiflu', 23, 121, 455);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (452, 'Correway Sunscreen (Non-waterproof)', 34, 305, 454);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (453, 'Zyprexa', 39, 283, 147);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (454, 'Paroxetine', 6, 257, 500);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (455, 'Scorodite Prunus', 13, 65, 111);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (456, 'Tretinoin', 6, 445, 444);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (457, 'Enflurane', 22, 220, 378);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (458, 'Cyclobenzaprine Hydrochloride', 28, 451, 500);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (459, 'HORIZANT', 47, 406, 354);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (460, 'Motion Medicine', 2, 377, 242);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (461, 'Ephinephrine', 47, 413, 403);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (462, 'Hydroxyzine Hydrochloride', 18, 201, 234);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (463, 'Dangsim K-7', 45, 487, 210);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (464, 'Tobramycin', 23, 445, 433);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (465, 'SAPHRIS', 26, 17, 292);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (466, 'Hydroxyzine Hydrochloride', 43, 163, 87);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (467, 'wal tussin', 31, 109, 329);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (468, 'Isopropyl Alcohol', 47, 232, 403);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (469, 'SHISEIDO RADIANT LIFTING FOUNDATION', 5, 231, 207);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (470, 'Ibuprofen', 12, 476, 156);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (471, 'Aveeno Calamine and Pramoxine Hydrochloride Anti Itch', 30, 89, 65);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (472, 'Care One Nicotine', 30, 299, 103);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (473, 'Oxybutynin Chloride', 29, 341, 95);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (474, 'HALIBUT', 13, 393, 181);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (475, 'Duloxetine', 18, 395, 382);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (476, 'Listerine', 46, 225, 290);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (477, 'ABILIFY', 34, 32, 156);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (478, 'Blistex Lip', 8, 153, 12);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (479, 'Quetiapine fumarate', 39, 469, 442);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (480, 'Night Time Cold/Flu Relief Original', 28, 374, 318);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (481, 'Sucralfate', 14, 424, 494);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (482, 'Anti-Bacterial Gentle Foaming Hand', 8, 15, 201);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (483, 'HAWAIIAN Tropic', 22, 200, 149);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (484, 'Next Choice One Dose', 6, 10, 474);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (485, 'Cystografin', 39, 34, 94);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (486, 'Ampicillin and Sulbactam', 15, 303, 433);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (487, 'Amiloride Hydrochloride', 16, 120, 448);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (488, 'Sodium Bicarbonate', 24, 207, 456);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (489, 'Phenylephrine HCl', 14, 359, 361);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (490, 'CLE DE PEAU BEAUTE FOUNDATION I', 2, 354, 241);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (491, 'Tramadol Hydrochloride', 4, 433, 89);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (492, 'CD HydraLife BB Creme Enhancing Sunscreen Moisturizer For Immediate Beauty Golden Peach Broad Spectrum SPF 30', 11, 179, 66);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (493, 'Pancreapar', 44, 362, 335);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (494, 'Propranolol Hydrochloride', 25, 53, 289);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (495, 'SOLIDAGO CANADENSIS POLLEN', 50, 485, 273);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (496, 'Naproxen', 49, 131, 189);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (497, 'SHISEIDO FUTURE SOLUTION LX TOTAL RADIANCE FOUNDATION', 39, 255, 481);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (498, 'Vicks VapoDrops', 15, 55, 365);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (499, 'Oxycodone and Acetaminophen', 44, 147, 483);
insert into Restaurants (RestaurantId, RestaurantName, Capacity, CityId, MenuId) values (500, 'Baclofen', 15, 271, 218);
